### ISSUE TITLE
Logo proposal for untitled game project

### ISSUE THREAD

**Issue by memoryskull** [kindness-is-the-dankest-meme/untitled-game-project#34]
Hi! @untitled-game-project
I'm interested in collaborating with this initiative by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by mysterycommand** [comment]
Hi @memoryskull, thank you for your interest, but we're not really at the "looking for logotype options" stage. This is more of a research/hobby project.
